//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityNode
    {
        public CityNode()
        {
            this.OriginRouteNodes = new HashSet<RouteNode>();
            this.DestinationRouteNodes = new HashSet<RouteNode>();
            this.OriginTreks = new HashSet<Trek>();
            this.DestinationTreks = new HashSet<Trek>();
        }
    
        public int CityNodeId { get; set; }
        public int RegionNodeId { get; set; }
        public string LanguageKey { get; set; }
    
        public virtual ICollection<RouteNode> OriginRouteNodes { get; set; }
        public virtual ICollection<RouteNode> DestinationRouteNodes { get; set; }
        public virtual RegionNode RegionNode { get; set; }
        public virtual ICollection<Trek> OriginTreks { get; set; }
        public virtual ICollection<Trek> DestinationTreks { get; set; }
    }
}
