//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackItem
    {
        public FeedbackItem()
        {
            this.FeedbackValues = new HashSet<FeedbackValue>();
        }
    
        public int FeedbackItemId { get; set; }
        public bool Mandatory { get; set; }
        public int SortNumber { get; set; }
        public bool IsNumeric { get; set; }
        public int FeedbackModelId { get; set; }
        public string NameTranslationKey { get; set; }
        public string DescriptionTranslationKey { get; set; }
    
        public virtual FeedbackModel FeedbackModel { get; set; }
        public virtual ICollection<FeedbackValue> FeedbackValues { get; set; }
    }
}
