//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public int RouteNodeId { get; set; }
        public int UserId { get; set; }
    
        public virtual RouteNode RouteNode { get; set; }
        public virtual User User { get; set; }
    }
}
