//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.StaticTranslations = new HashSet<StaticTranslation>();
            this.MapObjectTranslations = new HashSet<MapObjectTranslation>();
            this.DynamicTranslations = new HashSet<DynamicTranslations>();
        }
    
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<StaticTranslation> StaticTranslations { get; set; }
        public virtual ICollection<MapObjectTranslation> MapObjectTranslations { get; set; }
        public virtual ICollection<DynamicTranslations> DynamicTranslations { get; set; }
    }
}
