//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionNode
    {
        public RegionNode()
        {
            this.CityNodes = new HashSet<CityNode>();
        }
    
        public int RegionNodeId { get; set; }
        public string LanguageKey { get; set; }
    
        public virtual ICollection<CityNode> CityNodes { get; set; }
    }
}
