//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranslationModelContainer : DbContext
    {
        public TranslationModelContainer()
            : base("name=TranslationModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<DynamicTranslations> DynamicTranslations { get; set; }
        public virtual DbSet<StaticTranslation> StaticTranslations { get; set; }
        public virtual DbSet<MapObjectTranslation> MapObjectTranslations { get; set; }
    }
}
