//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trek
    {
        public string Hash { get; set; }
        public string Track { get; set; }
        public long TrekId { get; set; }
        public int OriginCityNodeId { get; set; }
        public int DesinationCityNodeId { get; set; }
        public byte NodesCount { get; set; }
        public System.DateTime TrekDate { get; set; }
    
        public virtual CityNode OriginCityNode { get; set; }
        public virtual CityNode DestinationCityNode { get; set; }
    }
}
