//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roads.DataBase.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
