
SET IDENTITY_INSERT [dbo].[RegionNodes] ON 
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (1, N'r-1')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (2, N'r-2')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (3, N'r-3')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (4, N'r-4')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (5, N'r-5')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (6, N'r-6')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (7, N'r-7')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (8, N'r-8')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (9, N'r-9')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (10, N'r-10')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (11, N'r-11')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (12, N'r-12')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (13, N'r-13')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (14, N'r-14')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (15, N'r-15')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (16, N'r-16')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (17, N'r-17')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (18, N'r-18')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (19, N'r-19')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (20, N'r-20')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (21, N'r-21')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (22, N'r-22')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (23, N'r-23')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (24, N'r-24')
INSERT [dbo].[RegionNodes] ([RegionNodeId], [LanguageKey]) VALUES (25, N'r-25')
SET IDENTITY_INSERT [dbo].[RegionNodes] OFF 
